Changed `string` to `string | number` in Routes Manifest types declaration
blitz-js/blitz pull request #2228
Opened 2021-04-17 12:24 UTC by JuanM04

### What are the changes and their implications?

Before this, something like this (taken from blitzjs.com) would throw a TypeScript error:

```tsx
<Link href={Routes.ProductsPage({ productId: 123 })} />
```

## Bug Checklist

- [x] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

2021-04-17 13:15 UTC, Skn0tt requested changes
Good catch! Could you add an integration test?

The CI fails, but I fail to see why ... any idea @flybayer?

2021-04-17 13:37 UTC, JuanM04 commented
> Could you add an integration test?

I've already changed `route-import-manifest.spec.ts` to match these changes. If you are asking me to create integration tests (the ones inside `test/`), I have no clue on how to create them.

> The CI fails, but I fail to see why

It failed before I created this PR (see #2223, for example)

2021-04-17 16:41 UTC, Mokshit06 commented
I think the CI is failing because we aren't running `blitz codegen` to [generate the Routes manifest](https://blitzjs.com/docs/route-manifest#generating).

2021-04-19 10:23 UTC, Skn0tt commented
@JuanM04 I've extended the existing integration test to include usage of numbers: 16dc11d

2021-04-19 10:24 UTC, Skn0tt commented
@Mokshit06

> I think the CI is failing because we aren't running blitz codegen to generate the Routes manifest.

It looks like Windows doesn't know how to deal with [these](https://github.com/blitz-js/blitz/tree/canary/packages/core/node_modules/.blitz) symlinks. Do you know of a way to make Symlinks work on windows? Otherwise, I'll just copy&paste the files they're linking to :)

2021-04-19 10:24 UTC, Skn0tt approved these changes

2021-04-19 19:29 UTC, merged