Fix wrong API requests when `trailingSlash` configuration is true
blitz-js/blitz pull request #2300
Opened 2021-05-04 19:16 UTC by peterpalau

Closes: #2294

### What are the changes and their implications?

This PR adds the implementation to consider the `trailingSlash` configuration in the API requests from either await direct function calls inside `useEffects` or `useQuery`.

## Checklist

- [x] Added `trailingSlash` to the blitz runtime dat
- [x] Updated `getApiUrlFromResolverFilePath` to add trailing slash if `getBlitzRuntimeData().trailingSlash` is true.

2021-05-06 14:54 UTC, flybayer requested changes
Thanks!!

Please add an integration test. You can do that by copying `test/integration/queries/` to `test/integration/trailing-slash/` and adding the trailing slash config to that.

2021-05-06 14:54 UTC, flybayer commented on packages/core/src/rpc-client.ts
> +  )
You need to contact the slash on end of resolverFilePath, not `api`. Current code will result in url like `/api//queries/getUser`

2021-05-24 12:50 UTC, cashmagnet commented
👋 are things happening here - I don't want to bug anyone for this, just want to know if I should pick it up if needed 🥰

2021-05-25 13:30 UTC, peterpalau commented
Hi @cashmagnet

>  are things happening here - I don't want to bug anyone for this, just want to know if I should pick it up if needed

I will be finishing this soon. Thank you.

2021-05-25 14:12 UTC, peterpalau commented
I'm sorry, things went wrong here. I'm going to discard this PR.

2021-05-25 14:12 UTC, closed without merging

2021-05-25 19:59 UTC, cashmagnet commented
I'm a little confused, I'm really sorry - I just don't want to steal your thunder ⚡ - does this mean you're gonna make another, or just want to be rid of this one and someone else should do it 😄

2021-05-28 15:14 UTC, flybayer commented
We have another PR opened for this: 2392