Add default auth options to authPlugin
blitz-js/blitz pull request #3548
Opened 2022-07-16 00:22 UTC by Zeko369

Closes: #3535

### What are the changes and their implications?

## Feature Checklist

- adds option to define `authenticate` or `redirectAuthenticated` on all pages by default and override them per page / layout

2022-07-16 22:53 UTC, dillonraphael approved these changes

2022-07-18 07:58 UTC, beerose commented
This is super cool! Thank you so much for this PR. 

We should also cover it in the docs and/or add an example to one of the apps in the `apps/` folder.

2022-07-22 10:46 UTC, flybayer commented on packages/blitz-auth/src/client/index.tsx
> +  defaults?: AuthPluginDefaultOptions
I think this will be a lot more clear what it is when reading the code
```suggestion
  pageDefaults?: AuthPluginDefaultOptions
```

2022-07-25 09:59 UTC, beerose reviewed
Looks great, but I have mixed feelings about using the word `factory` 😬 As it's a naming convention from class-based programming

2022-07-25 09:59 UTC, beerose commented on packages/blitz-auth/src/client/index.tsx
> +function withBlitzAuthPluginFactory(pageDefaults?: AuthPluginDefaultOptions) {
```suggestion
function createBlitzAuthPlugin(pageDefaults?: AuthPluginDefaultOptions) {
```

2022-07-25 09:59 UTC, beerose commented on packages/blitz-auth/src/client/index.tsx
> +    withProvider: withBlitzAuthPluginFactory(options.pageDefaults),
```suggestion
    withProvider: createBlitzAuthPlugin(options.pageDefaults),
```

2022-07-26 12:03 UTC, beerose requested changes
Looks good! Please make sure to add docs before merging

2022-07-28 20:26 UTC, Zeko369 commented
@beerose will do tomorrow

2023-03-30 20:06 UTC, closed without merging