Add AuthenticatedSessionContext to the codemod import map
blitz-js/blitz pull request #3771
Opened 2022-08-22 18:41 UTC by dillonraphael

Closes: #3769 
### What are the changes and their implications?

We were missing `AuthenticatedSessionContext` from the codemod import map

2022-08-23 08:26 UTC, beerose requested changes
Could you update the docs too?

2022-08-23 14:48 UTC, dillonraphael commented
> Could you update the docs too?

https://github.com/blitz-js/blitzjs.com/pull/749

2022-08-24 09:00 UTC, beerose commented on .changeset/early-lamps-itch.md
> +Add AuthenticatedSessionContext to the codemod import map
```suggestion
Add `AuthenticatedSessionContext` to the `upgrade-legacy` codemod import map
```

2022-08-24 09:00 UTC, beerose approved these changes

2022-08-24 09:09 UTC, merged