Migrate console
blitz-js/blitz pull request #3863
Opened 2022-09-25 10:23 UTC by siddhsuresh

Closes: #3862

### What are the changes and their implications?

- [x] migrate required files from legacy framework repo 
- https://github.com/blitz-js/legacy-framework/blob/main/nextjs/packages/next/cli/next-console.ts
- https://github.com/blitz-js/legacy-framework/blob/main/packages/cli/src/commands/console.ts
- [x] use ```esbuild``` than ```ts-node``` with reference to https://github.com/blitz-js/blitz/issues/1098#issuecomment-823670547 
- [x] add ```--skip-preload``` argument to allow users to only load the ```db``` module in the initial load of the console but allow  usage other modules when changes are made

2022-09-26 11:34 UTC, beerose requested changes
This is amazing work! Thank you!

I started testing it and it looks like top-level await doesn't work:

<img width="498" alt="CleanShot 2022-09-26 at 13 31 40@2x" src="https://user-images.githubusercontent.com/9019397/192265988-ebfd7f79-ac91-407c-904f-15a671fe0c0a.png">

2022-09-26 13:37 UTC, siddhsuresh commented
> This is amazing work! Thank you!
> 
> I started testing it and it looks like top-level await doesn't work:
> 
> <img alt="CleanShot 2022-09-26 at 13 31 40@2x" width="498" src="https://user-images.githubusercontent.com/9019397/192265988-ebfd7f79-ac91-407c-904f-15a671fe0c0a.png">

Hey @beerose, I am not getting that error on my end. I just tested in ubuntu through WSL2 and here is the terminal output. (Ignore the speed of my terminal, WSL2 in my laptop is very slow 😅)

[![asciicast](https://asciinema.org/a/rrMs9Lb6xl51GB68am0mRtETk.svg)](https://asciinema.org/a/rrMs9Lb6xl51GB68am0mRtETk)

2022-09-26 13:42 UTC, beerose commented
Hmm, that's interesting! I wouldn't expect it to be OS related, but maybe it is? I'm on macos, Node 16.

2022-09-26 13:47 UTC, siddhsuresh commented
> Hmm, that's interesting! I wouldn't expect it to be OS related, but maybe it is? I'm on macos, Node 16.

@beerose I am not sure what is going wrong because it works for me on both windows 11 and in ubuntu

2022-09-28 07:05 UTC, siddhsuresh commented
> This is amazing work! Thank you!
> 
> I started testing it and it looks like top-level await doesn't work:
> 
> <img alt="CleanShot 2022-09-26 at 13 31 40@2x" width="498" src="https://user-images.githubusercontent.com/9019397/192265988-ebfd7f79-ac91-407c-904f-15a671fe0c0a.png">

@beerose After researching how the REPL works with top level await, I have introduced this fix.
Now users can write commands without writing the ```await``` as I have overridden the eval code of the NodeJS REPL to resolve all commands as promises

### Before
![image](https://user-images.githubusercontent.com/83594610/192710464-4e743425-8919-472e-b149-45b2d88c97f5.png)

### After 
![image](https://user-images.githubusercontent.com/83594610/192710523-c48bee20-7ef7-4c9c-b0b4-ad743fdae471.png)

Does this solve the problem on your end?

2022-09-28 09:29 UTC, beerose commented
@siddhsuresh we should also change the message:

```
Tips: - Exit by typing .exit or pressing Ctrl-D
      - Use your db like this: await db.project.findMany()
      - ...
```

(remove the await)

2022-09-28 09:35 UTC, beerose commented
@siddhsuresh I was also thinking about the `skip-preload` and I'm not sure it's obvious what it means (if someone didn't read the docs first). Maybe we can call thins flag `--skip-resolvers`?

2022-09-28 09:40 UTC, siddhsuresh commented
> @siddhsuresh I was also thinking about the `skip-preload` and I'm not sure it's obvious what it means (if someone didn't read the docs first). Maybe we can call thins flag `--skip-resolvers`?

@beerose yeah I agree, I had given the flag name by taking reference from #3858, but also was thinking of changing it to ```only-db``` because it is exactly what the flag would do. What are your thoughts on this? 
If this would not be suitable I agree with naming it ```skip-resolvers```

2022-09-28 09:48 UTC, beerose commented
> > @siddhsuresh I was also thinking about the `skip-preload` and I'm not sure it's obvious what it means (if someone didn't read the docs first). Maybe we can call thins flag `--skip-resolvers`?
> 
> @beerose yeah I agree, I had given the flag name by taking reference from #3858, but I was also thinking of changing it to `--only-db` because it is exactly what the flag would do. What are your thoughts on this? If this would not be suitable I agree with naming it `skip-resolvers`

I was also thinking about `only-db` or `db-only`, so totally up to you :)

2022-09-28 09:59 UTC, siddhsuresh commented
> > > @siddhsuresh I was also thinking about the `skip-preload` and I'm not sure it's obvious what it means (if someone didn't read the docs first). Maybe we can call thins flag `--skip-resolvers`?
> > 
> > 
> > @beerose yeah I agree, I had given the flag name by taking reference from #3858, but I was also thinking of changing it to `--only-db` because it is exactly what the flag would do. What are your thoughts on this? If this would not be suitable I agree with naming it `skip-resolvers`
> 
> I was also thinking about `only-db` or `db-only`, so totally up to you :)

@beerose I have changed the flag name to ```--only-db```

2022-09-28 11:22 UTC, beerose approved these changes
Amazing work!

2022-09-28 11:22 UTC, beerose commented on .changeset/spotty-zoos-film.md
> +Migrate console
Add `blitz console` CLI command back to toolkit

2022-09-29 17:23 UTC, dillonraphael approved these changes

2022-09-29 20:22 UTC, merged