support invalidate all queries
blitz-js/blitz pull request #3899
Opened 2022-10-13 20:19 UTC by datner

Closes: an issue that bothered me

### What are the changes and their implications?

Support `invalidateQueries` not requiring any input, mirroring the original api
before
```ts
invalidateQueries(resolver, params)
invalidateQueries(resolver)
getQueryClient().invalidateQueries()
```
after
```ts
invalidateQueries(resolver, params)
invalidateQueries(resolver)
invalidateQueries()
```

## Bug Checklist

- [ ] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

## Feature Checklist

- [ ] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)
- [ ] Documentation added/updated (submit PR to [blitzjs.com repo `main` branch](https://github.com/blitz-js/blitzjs.com))

2022-11-09 21:09 UTC, datner commented
@beerose any updates?

2022-11-10 22:29 UTC, dillonraphael commented
Hey @datner pretty straight forward PR. Just need to fix the pnpmlock issue with the CI

2022-11-10 22:32 UTC, dillonraphael requested changes

2022-11-10 22:32 UTC, dillonraphael commented on .changeset/stupid-rabbits-jump.md
> +"@blitzjs/rpc": minor
```suggestion
"@blitzjs/rpc": patch
```

2022-11-10 22:38 UTC, datner commented on .changeset/stupid-rabbits-jump.md
> +"@blitzjs/rpc": minor
committed 🤓

2022-11-10 22:41 UTC, datner commented
@dillonraphael no idea how to solve the pnplock issue, had it for all my prs..
I would greatly appreciate it if you could do it for me or guide me through it
Feel free to commit in my pr btw, I don't mind

2022-12-20 20:09 UTC, dillonraphael approved these changes

2022-12-20 20:09 UTC, merged