Reference `vitest.config.ts` instead of jest for README|s
blitz-js/blitz pull request #4019
Opened 2022-12-23 14:36 UTC by tordans

- The readmes reference the file that is present, now
- `apps/toolkit-app-passportjs/README.md` still uses jest, so that stayed as is

2022-12-28 14:08 UTC, dillonraphael requested changes

2022-12-28 14:08 UTC, dillonraphael commented on apps/toolkit-app/README.md
> +- `vitest.config.ts` contains config for Vitest tests. You can [customize it if needed](https://vitejs.dev/config/).
```suggestion
├── vitest.config.ts
```

2022-12-29 13:40 UTC, tordans commented
@dillonraphael thanks for the review an fix.

- Could you give a hint at the question from the PR description: 
  >  Is it by design, that some folders have a vitest.config.ts and .js file? I picket the .ts file for the readme…
- This PR requires a changeset, yes? Something like "Update README|s to reference vitest instead of jest"

2022-12-29 18:48 UTC, dillonraphael commented
> @dillonraphael thanks for the review an fix.
> 
> * Could you give a hint at the question from the PR description:
>   > Is it by design, that some folders have a vitest.config.ts and .js file? I picket the .ts file for the readme…
> * This PR requires a changeset, yes? Something like "Update README|s to reference vitest instead of jest"

Not by design. Ideally we should be using .ts

Also I wouldn't say this PR needs a changeset. I tagged it as such.

2022-12-29 19:51 UTC, dillonraphael approved these changes

2022-12-29 19:51 UTC, merged