Next 13: Remove anchor tags from Link component
blitz-js/blitz pull request #4071
Opened 2023-01-28 22:11 UTC by tordans

Closes: https://github.com/blitz-js/blitz/issues/4066

### What are the changes and their implications?

Change all `<Link><a className="foo">Foo</a></Link>` to `<Link className="foo">Foo</Link>` in this repo.

## Bug Checklist

- [x] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

2023-01-30 05:48 UTC, siddhsuresh requested changes
I feel these `passHref` prop are no longer required.

2023-01-30 05:49 UTC, siddhsuresh commented on .changeset/swift-glasses-laugh.md
> +"@blitzjs/recipe-ghost": patch
```suggestion
"@blitzjs/generator": patch
```

2023-01-30 05:49 UTC, siddhsuresh commented on apps/toolkit-app-passportjs/src/auth/components/LoginForm.tsx
>            <Link href={Routes.ForgotPasswordPage()} passHref>
```suggestion
          <Link href={Routes.ForgotPasswordPage()}>
```

2023-01-30 05:49 UTC, siddhsuresh commented on apps/toolkit-app-passportjs/src/auth/components/LoginForm.tsx
>          <Link href={Routes.SignupPage()} passHref>
```suggestion
        <Link href={Routes.SignupPage()}>
```

2023-01-30 05:49 UTC, siddhsuresh commented on apps/toolkit-app-passportjs/src/pages/index.tsx
> +        <Link href={Routes.SignupPage()} passHref className="button small">
```suggestion
        <Link href={Routes.SignupPage()}className="button small">
```

2023-01-30 05:49 UTC, siddhsuresh commented on apps/toolkit-app-passportjs/src/pages/index.tsx
> +        <Link href={Routes.LoginPage()} passHref className="button small">
```suggestion
        <Link href={Routes.LoginPage()} className="button small">
```

2023-01-30 05:49 UTC, siddhsuresh commented on apps/toolkit-app/src/auth/components/LoginForm.tsx
>            <Link href={Routes.ForgotPasswordPage()} passHref>
```suggestion
          <Link href={Routes.ForgotPasswordPage()}>
```

2023-01-30 05:49 UTC, siddhsuresh commented on apps/toolkit-app/src/auth/components/LoginForm.tsx
>          <Link href={Routes.SignupPage()} passHref>
```suggestion
        <Link href={Routes.SignupPage()}>
```

2023-01-30 05:50 UTC, siddhsuresh commented on .changeset/swift-glasses-laugh.md
> +"@blitzjs/recipe-ghost": patch
The other 3 packages are ignored by changesets, causing the test failure.

2023-01-31 15:32 UTC, tordans commented
@siddhsuresh I apply your review, squashed and force pushed for a clean history. Let me know if I can help with anything else.

2023-01-31 15:50 UTC, siddhsuresh approved these changes

2023-02-03 04:14 UTC, Yansongsongsong commented
Hi there. It seems that for initialized scaffold, not only anchor tag in Link component but also issues on SSR and some class name in html labels.

can see the details here: https://github.com/blitz-js/blitz/issues/4066#issuecomment-1409666064

2023-02-03 10:41 UTC, tordans commented
@Yansongsongsong but those are separate issues. 
My personal take it: This would go faster, if we split them up in separate issues and if someone would create a PR for fixing them :-).

2023-02-06 13:15 UTC, flybayer approved these changes

2023-02-06 13:22 UTC, merged