fix: type error in reset-password.tsx
blitz-js/blitz pull request #4081
Opened 2023-02-10 23:23 UTC by exKAZUu

Follow up: #4051

### What are the changes and their implications?

Changes in #4051 cause an type error since `token` may be null.
This PR also removes unused an import statement.

## Bug Checklist

- [ ] Changeset added (run `pnpm changeset` in the root directory)
- [ ] Integration test added (see [test docs](https://blitzjs.com/docs/contributing#running-tests) if needed)

2023-02-11 10:34 UTC, tordans commented
Sorry about that.

However with this change the UI will fail silently, right?

In https://github.com/blitz-js/blitz/pull/4051#discussion_r1092191342 i suggested to add states for this that levied an explicit message. 

Another option would be to set the token to "not provided" so it fails the mutation and shows an error.

2023-02-13 10:07 UTC, flybayer requested changes

2023-02-13 10:07 UTC, flybayer commented on packages/generator/templates/app/src/pages/auth/reset-password.tsx
> +              token && await resetPasswordMutation({ ...values, token })
thanks for the PR! 

instead of this, we should add an `assert` statement just above this line :)

2023-02-13 12:57 UTC, exKAZUu commented
Thank you for your comments! I've added `assert` statement instead of failing silently.

2023-02-16 17:16 UTC, flybayer approved these changes

2023-02-16 17:16 UTC, merged