Fix for Tailwind recipe
blitz-js/blitz pull request #4165
Opened 2023-06-28 18:14 UTC by Zamfi99

The Tailwind recipe is going to add tailwindcss, autoprefixer and postcss to the project dependencies and based on [TailwindCSS documentation](https://tailwindcss.com/docs/installation) those should live in devDependecies. The first commit addresses this fix.

The default tailwind.config.js configuration file added by the recipe is set wrong due to content being ["{pages,app}/**/*.{js,ts,jsx,tsx}"] which will cause the node process to run into a heap error (there's no directory being named app). The second commit addresses this fix.

2023-07-06 09:00 UTC, siddhsuresh approved these changes

2023-07-11 13:41 UTC, siddhsuresh requested changes

2023-10-03 14:22 UTC, flybayer commented on recipes/tailwind/templates/config/tailwind.config.js
> +  content: ["./src/**/*.{js,ts,jsx,tsx}"],
```suggestion
  content: ["./{src,app,pages}/**/*.{js,ts,jsx,tsx}"],
```

2023-10-03 14:23 UTC, flybayer approved these changes

2023-10-05 14:19 UTC, siddhsuresh approved these changes

2023-10-05 14:24 UTC, merged